#启动端口
server:
  port: 8080
#项目路径
  servlet:
    context-path: /booksManageBoot
spring:
#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: lyx0122.

# 配置 JPA#
  jpa:
    hibernate:
#更新策略
      ddl-auto: update

#打印SQL#
    show-sql: true
#自动生成表结构
    generate-ddl: true
#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
#将sql语句打印到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
